### ISSUE TITLE
[기획] 8월 둘째주 기획안 전달

### ISSUE THREAD

**Issue by Bae-Heejin** [TeamChaRo/Charo-Plan#10]
## 📌 Title

매주차 지자체 메일 전송 5군데 / 전화 5군데 -> 컨텐츠 2개 이상 꼭 확보 목표로

## 📝  To-do

- [ ] 다빈 - 지자체 메일 전송
- [ ] 다빈 - 지자체 전화 
- [ ] 희진 - 지자체 메일 전송
- [ ] 희진 - 지자체 전화
